AWSTemplateFormatVersion : 2010-09-09
Transform: AWS::Serverless-2016-10-31

Description: An IAM Git auditor that log CloudTrail events related to IAM to Git.

Resources:

  Queue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: iam-audit
      KmsMasterKeyId: alias/aws/sqs

  Tailer:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      CodeUri: s3://iam-git-auditor/tailer.zip
      Handler: tailer
      Policies:
        - S3ReadPolicy:
            BucketName: cloudtrail-907251231013
        - SQSSendMessagePolicy:
            QueueName: !GetAtt Queue.QueueName
      Environment:
        Variables:
          QUEUE_URL: !Ref Queue

  TailerNotifier:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref Tailer
      Principal: s3.amazonaws.com
      SourceArn: arn:aws:s3:::iam-git-auditor

  Auditor:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      CodeUri: s3://iam-git-auditor/auditor.zip
      Handler: auditor
      ReservedConcurrentExecutions: 1
      Policies:
        - SQSPollerPolicy:
            QueueName: !GetAtt Queue.QueueName
      Environment:
        Variables:
          AWS_SECRETS_MANAGER_SECRET_NAME: IamGitAuditor
          GIT_REPO: https://github.com/dlabey/test.git

  AuditorTrigger:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      Enabled: false
      EventSourceArn: !GetAtt Queue.Arn
      FunctionName: !Ref Auditor